(()=>{'use strict';
const C=ChapiCore,KEY='chapi-training-v2',OLDKEY='chapi-training-v1',BACKUP='chapi-training-v2-before-v3',RESTORE='chapi-training-before-restore',VERSION='3.4';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),today=()=>C.iso(new Date()),round=(n,d=0)=>Number(n).toLocaleString('ja-JP',{maximumFractionDigits:d}),signed=n=>(n>0?'+':n===0?'±':'')+round(n),color=n=>n===null?'':n<0?'negative':n>0?'positive':'neutral';
let store,blocked=false,recoveryExported=false,externalConflict=false,rawOriginal='',current=today(),draft,savedDraft='',activeTab='record',month=current.slice(0,7)+'-01',selectedDetail=current,editing=null,targetsDraft=null,goalDraft=null,graphMode='weight',graphWeek=current,noticeTimer,settingsDirty=false,loadedToday=today();
const dirtySections=new Set();function markDirty(section){dirtySections.add(section);settingsDirty=true}function cleanSection(section){dirtySections.delete(section);settingsDirty=dirtySections.size>0}
function notice(s){$('notice').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{$('notice').textContent=''},6000)}
function download(obj,name){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([typeof obj==='string'?obj:JSON.stringify(obj,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
try{rawOriginal=localStorage.getItem(KEY)||'';const old=localStorage.getItem(OLDKEY);store=rawOriginal?C.migrate(JSON.parse(rawOriginal)):old?C.migrate(C.fromV1(JSON.parse(old))):C.fresh();if(rawOriginal&&Number(JSON.parse(rawOriginal).schemaRevision||0)<3&&!localStorage.getItem(BACKUP))localStorage.setItem(BACKUP,rawOriginal)}catch(e){blocked=true;store=C.fresh();$('fatal').classList.remove('hidden');$('fatal').innerHTML='<b>保存データを安全に読み込めませんでした。</b><p>元データを上書きせず、保存を停止しています。</p><button id="recoverRaw">元データを書き出す</button><p>'+esc(e.message)+'</p>';$('recoverRaw').onclick=()=>{download(rawOriginal||'', 'chapi-recovery.json');recoveryExported=true;notice('元データを書き出しました。設定から正常なバックアップを復元できます。')}}
function persist(next=store){if(blocked){notice('元データ保護のため保存を停止しています。先に書き出してください。');return false}try{localStorage.setItem(KEY,JSON.stringify(next));store=next;return true}catch(e){notice('保存できませんでした。入力は画面に残っています。空き容量を確認しバックアップしてください。');return false}}
// Do not overwrite storage at startup: migration is committed only on an explicit save.
function chooseDate(day){current=day;draft=C.normalizeDay(store.days[day]);savedDraft=JSON.stringify(draft);$('recordDate').value=day;$('weight').value=draft.weight??'';$('daynote').value=draft.note||'';$('restDay').checked=!!draft.restDay;renderExercises();renderStrengthTotal();renderFood();renderEnergy();renderWeek()}
function sync(){if(!draft)return;draft.weight=$('weight').value;draft.note=$('daynote').value;draft.restDay=$('restDay').checked;}
function dayDirty(){sync();return JSON.stringify(draft)!==savedDraft}
function changeDate(day){if(!C.date(day)){notice('日付を確認してください');return false}if(day!==current&&dayDirty()&&!confirm('未保存の変更があります。保存せず日付を切り替えますか？')){$('recordDate').value=current;return false}if(day!==current)chooseDate(day);return true}
function saveDay(){sync();if(draft.weight!==''&&(!C.nonnegative(draft.weight)||Number(draft.weight)<1||Number(draft.weight)>500)){notice('体重は1〜500 kgで入力してください');return false}for(const [key] of C.meals)for(const f of ['kcal','p','f','c']){const v=draft.meals?.[key]?.[f];if(v!==''&&v!=null&&!C.nonnegative(v)){notice('食事は0以上の数値で入力してください');return false}}if(draft.strengthWorkout){for(const f of ['minutes','kcal']){const v=draft.strengthWorkout[f];if(v!==''&&v!=null&&!C.nonnegative(v)){notice('筋トレ全体の時間・消費カロリーは0以上にしてください');return false}}}for(const sess of draft.sessions)for(const it of sess.items){for(const f of ['minutes','km','steps','kcal','rounds'])if(it[f]!==''&&it[f]!=null&&!C.nonnegative(it[f])){notice('運動の数値は0以上にしてください');return false}for(const st of it.sets||[])for(const f of ['kg','reps','rir'])if(st[f]!==''&&st[f]!=null&&!C.nonnegative(st[f])){notice('セットの数値を確認してください');return false}}const next=C.clone(store);next.days[current]=C.clone(draft);if(!persist(next))return false;savedDraft=JSON.stringify(draft);notice('この日の記録と食事を保存しました');renderEnergy();renderWeek();if(activeTab==='calendar')renderCalendar();return true}
function switchTab(name){if(name===activeTab)return;if(activeTab==='settings'&&name!=='settings'&&settingsDirty&&!confirm('設定に未保存の変更があります。設定を保存せず移動しますか？'))return;sync();activeTab=name;for(const p of document.querySelectorAll('.page'))p.classList.toggle('hidden',p.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='record'){renderEnergy();renderWeek()}if(name==='food')renderFood();if(name==='calendar')renderCalendar();if(name==='progress')renderGraphs();if(name==='history')renderHistory();if(name==='templates')renderTemplates();if(name==='settings'){renderSettings();dirtySections.clear();settingsDirty=false}window.scrollTo?.({top:0,behavior:'smooth'})}
function numberInput(label,value,change,{step='0.1',min='0',max,placeholder='未入力'}={}){const box=document.createElement('label');box.textContent=label;const input=document.createElement('input');input.type='number';input.inputMode=step==='1'?'numeric':'decimal';input.min=min;input.step=step;if(max)input.max=max;input.value=value??'';input.placeholder=placeholder;input.oninput=()=>change(input.value);box.append(input);return box}
function textInput(label,value,change,area=false){const box=document.createElement('label');box.textContent=label;const input=document.createElement(area?'textarea':'input');input.value=value??'';input.oninput=()=>change(input.value);box.append(input);return box}
function button(label,fn,cls='outline'){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;return b}
function selectInput(label,value,options,change){const box=document.createElement('label');box.textContent=label;const input=document.createElement('select');for(const [v,text] of options)input.add(new Option(text,v));input.value=value??'';input.onchange=()=>change(input.value);box.append(input);return box}
function refreshPickers(){for(const kind of ['strength','cardio']){const root=$(kind+'Picker');root.innerHTML='';for(const t of store.templates)if(t.items.some(i=>(i.kind==='cardio')===(kind==='cardio')))root.add(new Option(t.name,t.id));$(kind==='strength'?'addStrengthSession':'addCardioSession').disabled=!root.options.length}}
function addSession(kind){sync();const t=store.templates.find(x=>x.id===$(kind+'Picker').value);if(!t)return;const items=t.items.filter(i=>(i.kind==='cardio')===(kind==='cardio')).map(i=>{const out={...C.clone(i),note:'',...(i.kind==='cardio'?{minutes:'',kcal:'',energyType:'unknown'}:{})};if(i.kind==='cardio'){out.km='';out.steps='';delete out.sets}else if(i.tracking==='rounds'){out.rounds='';out.done=false;delete out.sets}else{const prev=C.previous(store,i.id,current),weights=(prev?.item.sets||[]).filter(s=>s.done);out.sets=Array.from({length:Math.max(1,Math.min(30,Number(i.sets)||3))},(_,n)=>({kg:weights[n]?.kg??weights.at(-1)?.kg??'',reps:'',rir:'',done:false}))}return out});draft.sessions.push({id:uid(),name:t.name,templateId:t.id,items});renderExercises();renderEnergy()}
function renderStrengthTotal(){const w=draft.strengthWorkout||{};$('strengthTotalMinutes').value=w.minutes??'';$('strengthTotalKcal').value=w.kcal??'';$('strengthTotalType').value=w.energyType||'unknown'}
function updateStrengthTotal(field,value){if(!draft.strengthWorkout)draft.strengthWorkout={minutes:'',kcal:'',energyType:'unknown'};draft.strengthWorkout[field]=value;renderEnergy()}
function renderExercises(){for(const kind of ['strength','cardio']){const root=$(kind+'Sessions');root.innerHTML='';let count=0;draft.sessions.forEach((sess,si)=>sess.items.forEach((it,ii)=>{if((it.kind==='cardio')!==(kind==='cardio'))return;count++;const wrap=document.createElement('article');wrap.className='exercise';const head=document.createElement('div');head.className='row';const h=document.createElement('h3');h.textContent=it.name||'名称未設定';head.append(h,button('削除',()=>{if(confirm('この日の「'+(it.name||'運動')+'」を削除しますか？ 保存するまでは確定しません。')){draft.sessions[si].items.splice(ii,1);if(!draft.sessions[si].items.length)draft.sessions.splice(si,1);renderExercises();renderEnergy()}},'danger button-small'));wrap.append(head);const origin=document.createElement('p');origin.className='hint';origin.textContent=sess.name||'';wrap.append(origin);if(it.annotation){const annotation=document.createElement('p');annotation.className='annotation';annotation.textContent=it.annotation;wrap.append(annotation)}
if(kind==='strength'){const details=document.createElement('details');details.innerHTML='<summary>前回の記録を見る</summary>';const previous=C.previous(store,it.id,current),box=document.createElement('div');box.className='previous';if(previous){const p=previous.item;box.innerHTML='<b>'+esc(previous.date)+'（閲覧のみ）</b>';const lines=(p.sets||[]).map((s,i)=>`${i+1}セット：${s.kg??'—'} kg × ${s.reps??'—'} 回 / RIR ${s.rir??'—'}${s.done?' ✓':''}`);if(p.rounds!==undefined)lines.unshift('周回数：'+(p.rounds||'未入力')+' 周');for(const line of lines){const el=document.createElement('p');el.textContent=line;box.append(el)}if(p.note){const note=document.createElement('p');note.textContent='備考：'+p.note;box.append(note)}}else box.textContent='前回記録なし';details.append(box);wrap.append(details);
if(it.tracking==='rounds'&&!Array.isArray(it.sets)){wrap.append(numberInput('周回数（周）',it.rounds,v=>{it.rounds=v;renderEnergy()},{step:'1'}));const ck=document.createElement('label');ck.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=!!it.done;input.onchange=()=>it.done=input.checked;ck.append(input,'完了');wrap.append(ck)}else{const labels=document.createElement('div');labels.className='set-head';labels.innerHTML='<span>#</span><span>重量 kg</span><span>回数</span><span>RIR</span><span>完了</span>';wrap.append(labels);(it.sets||[]).forEach((st,n)=>{const row=document.createElement('div');row.className='set-row';const idx=document.createElement('span');idx.textContent=n+1;row.append(idx);for(const f of ['kg','reps','rir']){const inp=document.createElement('input');inp.type='number';inp.inputMode='decimal';inp.min='0';inp.step=f==='kg'?'0.5':'1';inp.value=st[f]??'';inp.setAttribute('aria-label',`${it.name} ${n+1}セット ${f==='kg'?'重量 kg':f==='reps'?'回数':'RIR'}`);inp.oninput=()=>st[f]=inp.value;row.append(inp)}const ck=document.createElement('input');ck.type='checkbox';ck.checked=!!st.done;ck.setAttribute('aria-label',`${it.name} ${n+1}セット 完了`);ck.onchange=()=>st.done=ck.checked;row.append(ck);wrap.append(row)});const acts=document.createElement('div');acts.className='actions';acts.append(button('＋セット',()=>{it.sets=it.sets||[];it.sets.push({kg:it.sets.at(-1)?.kg??0,reps:'',rir:'',done:false});renderExercises()}),button('−セット',()=>{if(it.sets?.length>1){const last=it.sets.at(-1);if((last.done||C.numeric(last.reps))&&!confirm('入力済みの最後のセットを削除しますか？'))return;it.sets.pop();renderExercises()}}));wrap.append(acts)}}
if(kind==='cardio'){const vals=document.createElement('div');vals.className='two';vals.append(numberInput('運動時間（分）',it.minutes,v=>{it.minutes=v;renderEnergy()},{step:'0.1'}));if(kind==='cardio'&&!it.noDistance)vals.append(numberInput('距離（km）',it.km,v=>it.km=v,{step:'0.01'}));if(kind==='cardio'&&!it.noDistance)vals.append(numberInput('歩数（歩・任意）',it.steps,v=>it.steps=v,{step:'1'}));wrap.append(vals);
const energyBox=document.createElement('div');energyBox.className='energy-inputs';energyBox.innerHTML='<h4>この運動の消費カロリー</h4>';energyBox.append(numberInput('入力値（kcal・空欄で削除）',it.kcal,v=>{it.kcal=v;renderEnergy()},{step:'1'}),selectInput('入力値の区分',it.energyType||'unknown',[['unknown','未確認（合計は未算出）'],['net','正味消費（安静時分を含まない）'],['gross','総消費（安静時分を含む）']],v=>{it.energyType=v;renderEnergy()}));const hint=document.createElement('p');hint.className='hint';hint.textContent='総消費は運動時間が必要です。まとめて計測したカロリーは一つの記録だけに入力し、各種目への重複入力を避けてください。未入力分は加算しません。';energyBox.append(hint);wrap.append(energyBox)}wrap.append(textInput('備考',it.note,v=>it.note=v,true));root.append(wrap)}));if(!count)root.innerHTML='<p class="hint">まだ登録がありません。メニューを選んで追加できます。</p>'}}
function renderLegacy(){const box=$('legacyEnergy');box.classList.toggle('hidden',!C.numeric(draft.calories));if(!C.numeric(draft.calories))return;box.innerHTML='<h2>旧記録の活動カロリー</h2><p>'+esc(draft.calories)+' kcal <small>元の入力値を保持</small></p><p class="hint">運動以外の活動を含む可能性があるため、運動の合計へは自動加算しません。内容が確認できた運動だけを個別登録してください。</p>';const label=document.createElement('label');label.className='check';const ck=document.createElement('input');ck.type='checkbox';ck.checked=!!draft.legacyCaloriesResolved;ck.onchange=()=>{draft.legacyCaloriesResolved=ck.checked;renderEnergy()};label.append(ck,'内容を確認済み（元の値は残す）');box.append(label)}
function renderEnergy(){if(!draft)return;sync();const e=C.energy(store,current,draft),target=Number(store.foodTargets?.kcal)||2000;$('energyHeading').textContent=(current===today()?'今日':'選択日')+'の推定総消費カロリー';$('energyDate').textContent=current+(current===today()?' · 今日':'');$('totalEnergy').innerHTML=e.total===null?'— <small>kcal</small>':round(e.total)+' <small>kcal</small>';$('energyBreakdown').textContent=e.base?`生活消費 ${round(e.base.life)} kcal ＋ 運動追加消費 ${round(e.exercise.net)} kcal${e.exercise.unresolved?'（確認済み分）':''}`:'プロフィール・生活活動・体重を設定すると表示します。';const cautions=[];if(e.exercise.unresolved)cautions.push('運動の区分／時間が未確認のため総消費は未算出です。');if(e.exercise.missing)cautions.push('運動カロリーの空欄は加算していません。');if(!draft.sessions.length)cautions.push('登録された運動の追加消費は0 kcalです（実際の運動量が0とは限りません）。');if(!e.food.complete)cautions.push('食事入力が未完了のため収支は暫定です。');if(e.legacy)cautions.push('旧活動カロリーは未確認・合計対象外です。');$('energyCaution').textContent=cautions.join(' ');$('intakeValue').textContent=e.food.count.kcal?round(e.food.total.kcal)+' kcal':'未記録';$('balanceValue').textContent=e.balance===null?'未算出':signed(e.balance)+' kcal';$('balanceValue').className=color(e.balance);const adjusted=target+Math.round(e.exercise.net*.7);$('baseDailyTarget').textContent=round(target)+' kcal';$('dailyTarget').textContent=round(adjusted)+' kcal';$('dailyProgress').value=Math.min(100,e.food.total.kcal/adjusted*100);$('dailyRemaining').textContent=e.food.count.kcal?(e.food.total.kcal<=adjusted?'今日の目標まで残り '+round(adjusted-e.food.total.kcal):'今日の目標を '+round(e.food.total.kcal-adjusted)+' 超過')+' kcal':'食事を入力すると進捗を表示します。';renderMascot(e,adjusted);$('energyDetails').innerHTML=e.base?`<p>基礎代謝 ${round(e.base.bmr)} kcal / 日<br>生活活動係数 ×${e.base.activity}<br>参照体重 ${e.base.w.weight} kg（${e.base.w.date}）<br>年齢 ${e.base.age}歳<br>体重維持の推定値 ${e.total===null?'未算出':round(e.total)+' kcal / 日'}<br>減量参考値 ${round(e.base.life-Math.min(400,e.base.life*.15))} kcal / 日（生活消費から最大15%・400 kcalを差し引く概算）</p>`:'<p class="hint">成人プロフィールと過去または当日の体重記録が必要です。</p>';}
function mascotAssessment(e,adjusted,rest=false){
 if(!e.food.count.kcal)return {face:'🤖',grade:'記録待ち',message:'食事を記録すると、一日のバランスを一緒に振り返れるよ！'};
 const ratio=e.food.total.kcal/adjusted,hasP=e.food.count.p>0,protein=hasP?e.food.total.p/Math.max(1,Number(store.foodTargets?.p)||130):null;
 let score=65;
 if(ratio>=.8&&ratio<=1.12)score+=20;else if(ratio>=.65&&ratio<=1.25)score+=8;else score-=20;
 if(protein!==null)score+=protein>=.8&&protein<=1.5?12:protein>=.55?3:-8;
 if(e.food.complete)score+=5;
 if(e.balance!==null&&e.balance< -900)score-=15;
 if(rest)score+=3;
 const grade=score>=90?'満点':score>=75?'良い':score>=60?'並':score>=40?'良くない':'悪い';
 const faces={'満点':'🤖✨','良い':'🤖💚','並':'🤖','良くない':'🤖💭','悪い':'🤖🌧️'};
 const message=rest?'今日は回復の日。食事と休息を大切にしよう！':ratio<.65?'摂取量が少なめかも。無理なカロリー不足には気をつけよう！':ratio>1.25?'少し目標を超えたね。明日また普段どおり続けよう！':protein!==null&&protein<.8?'食事の記録、いい感じ！たんぱく質も意識してみよう。':'記録できてえらい！無理なく続けることが一番大切だよ。';
 return {face:faces[grade],grade,message};
}
function renderMascot(e,adjusted){const m=mascotAssessment(e,adjusted,!!draft.restDay);$('mascotFace').textContent=m.face;$('mascotGrade').textContent=m.grade;$('mascot').dataset.message=m.message;$('mascotMessage').classList.add('hidden')}
function renderFood(){const totals=C.foodTotals(draft);$('foodDate').textContent=current;$('foodInputs').innerHTML='';for(const [key,name] of C.meals){const wrap=document.createElement('div');wrap.className='meal';const heading=document.createElement('h3');heading.textContent=name;wrap.append(heading);const grid=document.createElement('div');grid.className='food-grid';for(const [field,label] of [['kcal','kcal'],['p','P（g）'],['f','F（g）'],['c','C（g）']]){const inp=numberInput(label,draft.meals?.[key]?.[field],v=>{draft.meals[key]={...(draft.meals[key]||{}),[field]:v};renderFoodSummary()});inp.querySelector('input').id=`food_${key}_${field}`;grid.append(inp)}wrap.append(grid);$('foodInputs').append(wrap)}$('foodComplete').checked=!!draft.foodComplete;renderFoodSummary()}
function renderFoodSummary(){const t=C.foodTotals(draft),targets=store.foodTargets||{},root=$('foodSummary');root.innerHTML='';for(const [f,label,unit] of [['kcal','摂取カロリー','kcal'],['p','タンパク質 P','g'],['f','脂質 F','g'],['c','炭水化物 C','g']]){const box=document.createElement('div');box.className='food-stat';const target=Number(targets[f]);box.innerHTML=`<span class="label">${label}</span><strong>${t.count[f]?round(t.total[f],1)+' <small>'+unit+'</small>':'未記録'}</strong><progress max="100" value="${target?Math.min(100,t.total[f]/target*100):0}"></progress><small>目標 ${Number.isFinite(target)?round(target,1)+' '+unit:'未設定'}${Number.isFinite(target)?'<br>残り '+round(target-t.total[f],1)+' '+unit:''}</small>`;root.append(box)}}
function dayReport(day,d){const e=C.energy(store,day,d),lines=[`【Chapi Fit ${day}】`,`体重：${C.numeric(d.weight)?d.weight+' kg':'未入力'}`,`摂取カロリー：${e.food.count.kcal?round(e.food.total.kcal)+' kcal':'未記録'}`,`推定総消費カロリー：${e.total===null?'未算出':round(e.total)+' kcal'}`,`カロリー収支：${e.balance===null?'未算出':signed(e.balance)+' kcal'}${e.provisional?'（暫定）':''}`];if(d.strengthWorkout){const w=d.strengthWorkout;lines.push('\n💪 筋トレ全体');if(C.numeric(w.minutes))lines.push('合計時間 '+w.minutes+' 分');if(C.numeric(w.kcal))lines.push('入力消費 '+w.kcal+' kcal（'+({net:'正味',gross:'総消費',unknown:'区分未確認'}[w.energyType||'unknown'])+'）')}for(const sess of d.sessions||[])for(const i of sess.items||[]){lines.push('\n'+(i.kind==='cardio'?'🏃 ':'💪 ')+i.name);if(i.rounds!==undefined)lines.push('周回数 '+(i.rounds||'未入力')+' 周');for(const [n,st] of (i.sets||[]).entries())lines.push(`${n+1}セット：${st.kg??'—'} kg × ${st.reps||'—'} 回 / RIR ${st.rir??'—'}${st.done?' ✓':''}`);if(i.kind==='cardio'&&C.numeric(i.minutes))lines.push('時間 '+i.minutes+' 分');if(C.numeric(i.km))lines.push('距離 '+i.km+' km');if(i.kind==='cardio'&&C.numeric(i.kcal))lines.push('入力消費 '+i.kcal+' kcal（'+({net:'正味',gross:'総消費',unknown:'区分未確認'}[i.energyType||'unknown'])+'）');if(i.note)lines.push('備考：'+i.note)}lines.push('\n'+foodReport(d));if(C.numeric(d.calories))lines.push('旧活動カロリー（保持・合計対象外）：'+d.calories+' kcal');if(d.restDay)lines.push('🌙 休息日');if(d.note)lines.push('メモ：'+d.note);return lines.join('\n')}
function foodReport(d){const lines=[];for(const [key,name] of C.meals){const m=d.meals?.[key]||{};if(Object.values(m).some(C.numeric))lines.push(`${name}：${C.numeric(m.kcal)?m.kcal:'—'} kcal / P ${C.numeric(m.p)?m.p:'—'} g / F ${C.numeric(m.f)?m.f:'—'} g / C ${C.numeric(m.c)?m.c:'—'} g`)}const t=C.foodTotals(d);lines.push(`入力合計：${round(t.total.kcal)} kcal / P ${round(t.total.p,1)} g / F ${round(t.total.f,1)} g / C ${round(t.total.c,1)} g`);return lines.join('\n')}
async function copy(text){try{await navigator.clipboard.writeText(text);notice('コピーしました')}catch(e){const a=document.createElement('textarea');a.value=text;document.body.append(a);a.select();try{if(!document.execCommand('copy'))throw Error();notice('コピーしました')}catch(e){prompt('コピーする内容',text)}a.remove()}}
function renderWeek(){const w=C.week(store,current,today());$('weekHeading').textContent=(C.weekStart(current)===C.weekStart(today())?'今週':'選択した週')+'のカロリー収支目標';$('weekDates').textContent=w.start+' 〜 '+w.end+'（月〜日・保存済み記録）';$('weekTarget').textContent=w.target===null?'体重目標を設定してください':signed(w.target)+' kcal / 週';$('weekSummary').innerHTML=`<p>記録済み累計 <b class="${color(w.sum)}">${w.count?signed(w.sum)+' kcal':'未算出'}</b>（${w.count}/7日）</p>${w.target!==null?'<p>目標との差 '+signed(w.left)+' kcal'+(w.rate===null?' ／ 維持目標のため達成率は表示しません':' ／ 達成率 '+round(w.rate,1)+'%')+'</p>':''}`;$('weekDaily').textContent=w.perDay===null?'':`残り${w.remaining}日（当日を含む）の参考収支：${signed(w.perDay)} kcal / 日。今日の記録も入力途中なら暫定です。`;const g=C.goalAt(store,current),base=C.baseEnergy(store,current),plan=g&&base?C.exercisePlan(g,base.life):null;
$('weekExercisePlan').innerHTML=plan?`<b>今週の運動・食事プラン</b><p>週間運動消費目標：${round(plan.exerciseWeekly)} kcal / 週 <small>（1日平均 ${round(plan.exerciseDaily)} kcal）</small><br>食事で確保するカロリー収支の目安：${signed(plan.foodWeekly)} kcal / 週 <small>（1日平均 ${signed(plan.foodDaily)} kcal）</small><br>運動計画を70％反映した摂取カロリー参考値：${round(plan.intakeDaily)} kcal / 日</p><p class="hint">計画値は実際のカロリー収支には加算しません。食事目標へ反映する場合は設定から手動で適用してください。</p>`:'<p class="hint">運動計画を確認するには体重目標とプロフィールを設定してください。</p>';
const weekExercise=w.dates.filter(day=>day<=today()&&store.days[day]).reduce((sum,day)=>{const v=C.energy(store,day);return sum+v.exercise.net},0);const exerciseGoal=Number(g?.exerciseWeeklyKcal)||0;$('weeklyExerciseSummary').innerHTML=`<b>🏃 今週の運動：${round(weekExercise)} / ${round(exerciseGoal)} kcal</b><progress max="100" value="${exerciseGoal?Math.min(100,weekExercise/exerciseGoal*100):0}"></progress><small>${exerciseGoal?'目標達成率 '+round(weekExercise/exerciseGoal*100,1)+'%':'運動目標は設定から登録できます'} ／ 保存済みの記録のみ集計</small>`;$('weekWarning').textContent=(w.complete<7?'入力不足があるため実績・進捗は暫定です。未記録日は0としていません。 ':'')+(w.perDay!==null&&Math.abs(w.perDay)>750?'日割り値が大きいため、無理な帳尻合わせはせず期間を見直してください。':'収支の符号だけで健康上の良否は判断できません。')}
function marks(d){const items=(d?.sessions||[]).flatMap(s=>s.items||[]);const strength=items.some(i=>i.kind!=='cardio'&&(i.done||Number(i.rounds)>0||(i.sets||[]).some(s=>s.done||C.numeric(s.reps)))),cardio=items.some(i=>i.kind==='cardio'&&(Number(i.minutes)>0||Number(i.km)>0||Number(i.steps)>0||Number(i.kcal)>0));return (strength?'💪':'')+(cardio?'🏃':'')+(C.foodTotals(d||{}).hasMark?'🍽️':'')}
function renderCalendar(){const root=$('calendarGrid');root.innerHTML='';const dt=C.date(month),year=dt.getFullYear(),m=dt.getMonth();$('calendarMonth').textContent=`${year}年${m+1}月`;for(const day of ['日','月','火','水','木','金','土']){const e=document.createElement('div');e.className='weekday';e.textContent=day;root.append(e)}for(let n=0;n<dt.getDay();n++)root.append(document.createElement('div'));const len=new Date(year,m+1,0).getDate();for(let n=1;n<=len;n++){const day=C.iso(new Date(year,m,n)),d=store.days[day],e=d?C.energy(store,day):null,b=button('',()=>{selectedDetail=day;renderCalendarDetail(day);renderCalendarSelection()},'');b.dataset.day=day;b.setAttribute('aria-label',day+' '+(e?.balance!=null?'カロリー収支 '+signed(e.balance)+' kcal':'収支未算出'));b.innerHTML=`<span class="day-num">${n}</span><span class="marks">${marks(d)||'　'}</span><span class="day-energy ${color(e?.balance??null)}">${e?.balance!=null?signed(e.balance)+(e.provisional?'*':''):'—'}</span><span class="unit">${e?.balance!=null?'kcal':''}</span>`;if(day===today())b.classList.add('today');root.append(b)}renderCalendarSelection();renderCalendarDetail(selectedDetail)}
function renderCalendarSelection(){document.querySelectorAll('[data-day]').forEach(b=>b.classList.toggle('selected',b.dataset.day===selectedDetail))}
function renderCalendarDetail(day){const box=$('calendarDetail'),d=store.days[day],e=d?C.energy(store,day):null;box.innerHTML='<h2>'+esc(day)+' の記録</h2>';if(!d)box.innerHTML+='<p class="hint">記録がありません。</p>';else box.innerHTML+=`<p>摂取カロリー：${e.food.count.kcal?round(e.food.total.kcal)+' kcal':'未記録'}<br>推定総消費カロリー：${e.total===null?'未算出':round(e.total)+' kcal'}<br>カロリー収支：<b class="${color(e.balance)}">${e.balance===null?'未算出':signed(e.balance)+' kcal'}</b>${e.provisional?'（暫定）':''}<br>体重：${C.numeric(d.weight)?esc(d.weight)+' kg':'未入力'}</p><p class="hint">${esc((d.sessions||[]).flatMap(s=>s.items.map(i=>(i.kind==='cardio'?'🏃 ':'💪 ')+i.name)).join(' / ')||'運動登録なし')}</p>`;box.append(button('この日を編集',()=>{if(changeDate(day))switchTab('record')}))}
function renderHistory(){const root=$('historyList');root.innerHTML='';const dates=Object.keys(store.days).sort().reverse();if(!dates.length){root.innerHTML='<p class="hint">まだ記録がありません。</p>';return}for(const day of dates){const d=store.days[day],e=C.energy(store,day),box=document.createElement('details');box.className='history-entry';const summary=document.createElement('summary');summary.innerHTML=`<span><b>${esc(day)}</b> ${marks(d)}${d.restDay?' 🌙':''}</span><span class="history-meta">体重 ${C.numeric(d.weight)?esc(d.weight)+' kg':'未入力'} <b class="${color(e.balance)}">${e.balance===null?'収支未算出':signed(e.balance)+' kcal'}</b></span>`;box.append(summary);const detail=document.createElement('div');detail.className='history-detail';const foods=e.food;detail.innerHTML=`<h3>🍽️ 食事</h3><p>摂取カロリー：<b>${foods.count.kcal?round(foods.total.kcal)+' kcal':'未記録'}</b></p><div class="history-macros">${[['p','P たんぱく質'],['f','F 脂質'],['c','C 炭水化物']].map(([k,label])=>`<div><small>${label}</small><b>${foods.count[k]?round(foods.total[k],1)+' g':'未記録'}</b></div>`).join('')}</div><h3>💪 運動</h3><p>${d.restDay?'🌙 休息日<br>':''}${esc((d.sessions||[]).flatMap(s=>(s.items||[]).map(i=>i.name)).join('、')||'運動登録なし')}</p><p>記録された正味消費：${round(e.exercise.net)} kcal${e.exercise.unresolved?'（未確認の運動あり）':''}</p><p class="hint">${e.provisional?'入力途中のため暫定値です。':''}</p>`;const actions=document.createElement('div');actions.className='actions';actions.append(button('この日を編集',()=>{if(changeDate(day))switchTab('record')}),button('報告コピー',()=>copy(dayReport(day,d))),button('削除',()=>{if(!confirm(day+' の記録を削除しますか？ 削除前コピーを端末内に保存します。'))return;try{localStorage.setItem('chapi-training-before-delete',JSON.stringify(store))}catch(e){notice('削除前コピーを保存できないため中止しました');return}const next=C.clone(store);delete next.days[day];if(persist(next)){if(current===day)chooseDate(day);renderHistory();notice('削除しました。直前コピーはバックアップ書き出しから復旧できます。')}},'danger'));detail.append(actions);box.append(detail);root.append(box)}}

function renderTemplates(){const root=$('templateList');root.innerHTML='';for(const t of store.templates){const box=document.createElement('div');box.className='template-card';box.innerHTML='<h3>'+esc(t.name)+'</h3><p class="hint">'+t.items.length+'種目 · '+esc(t.items.slice(0,2).map(i=>i.name).join(' / '))+(t.items.length>2?' ほか'+(t.items.length-2)+'種目':'')+'</p>';const actions=document.createElement('div');actions.className='actions';actions.append(button('編集',()=>startEditor(t)),button('複製',()=>{const next=C.clone(store),x=C.clone(t);x.id=uid();x.name+='（コピー）';next.templates.push(x);if(persist(next)){renderTemplates();refreshPickers()}}),button('削除',()=>{if(!confirm('「'+t.name+'」を削除しますか？ 過去の記録は残ります。'))return;const next=C.clone(store);next.templates=next.templates.filter(x=>x.id!==t.id);if(persist(next)){renderTemplates();refreshPickers()}},'danger'));box.append(actions);root.append(box)}}
function startEditor(t){editing=t?C.clone(t):{id:uid(),name:'',items:[]};$('templateName').value=editing.name;$('templateEditor').classList.remove('hidden');renderEditor();$('templateEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function renderEditor(){const root=$('templateItems');root.innerHTML='';editing.items.forEach((it,i)=>{const box=document.createElement('div');box.className='template-item';const row=document.createElement('div');row.className='row';const title=document.createElement('h3');title.textContent=`${i+1}．${it.kind==='cardio'?'有酸素':'筋トレ'}`;row.append(title);const controls=document.createElement('div');controls.className='actions';const up=button('↑',()=>{[editing.items[i-1],editing.items[i]]=[editing.items[i],editing.items[i-1]];renderEditor()});up.disabled=i===0;up.setAttribute('aria-label','種目を上へ');const down=button('↓',()=>{[editing.items[i+1],editing.items[i]]=[editing.items[i],editing.items[i+1]];renderEditor()});down.disabled=i===editing.items.length-1;down.setAttribute('aria-label','種目を下へ');controls.append(up,down,button('削除',()=>{editing.items.splice(i,1);renderEditor()},'danger'));row.append(controls);box.append(row,textInput('種目名',it.name,v=>it.name=v),textInput('名称直下の注釈（任意）',it.annotation,v=>it.annotation=v,true));if(it.kind!=='cardio'){box.append(selectInput('記録方式',it.tracking||'sets',[['sets','セット・重量・回数'],['rounds','周回数（サーキット）']],v=>{it.tracking=v;renderEditor()}));if(it.tracking==='rounds')box.append(numberInput('目安の周回数（周）',it.rounds||2,v=>it.rounds=v,{min:'1',step:'1'}));else{box.append(numberInput('初期セット数',it.sets,v=>it.sets=v,{step:'1',min:'1',max:'30'}))}}else{const l=document.createElement('label');l.className='check';const ck=document.createElement('input');ck.type='checkbox';ck.checked=!!it.noDistance;ck.onchange=()=>it.noDistance=ck.checked;l.append(ck,'距離・歩数欄を表示しない（ステッパー等）');box.append(l)}root.append(box)})}
function saveTemplate(){editing.name=$('templateName').value.trim();if(!editing.name||editing.items.some(i=>!i.name.trim())){notice('メニュー名・種目名を入力してください');return}for(const i of editing.items){if(i.kind!=='cardio'&&i.tracking!=='rounds'){if(!Number.isInteger(Number(i.sets))||i.sets<1||i.sets>30){notice('初期セット数（1〜30）を確認してください');return}i.sets=Number(i.sets)}if(i.tracking==='rounds'&&(!Number.isInteger(Number(i.rounds))||i.rounds<1||i.rounds>100)){notice('周回数の目安は1〜100周にしてください');return}}const next=C.clone(store),idx=next.templates.findIndex(x=>x.id===editing.id);if(idx>=0)next.templates[idx]=C.clone(editing);else next.templates.push(C.clone(editing));if(persist(next)){editing=null;$('templateEditor').classList.add('hidden');renderTemplates();refreshPickers();notice('メニューを保存しました')}}
const activityOptions=[['1.2','座り仕事中心／休日は休息','机での仕事が中心。運動を除き3,000歩未満、立つ・歩く時間は1日30分未満が多い。'],['1.375','立ち仕事や移動が多い','接客や軽い工場内移動。運動を除き3,000〜6,000歩、立つ・歩く時間は1日30〜90分程度。'],['1.55','日常的に身体を動かす','配送・巡回・家事などでよく動く。運動を除き6,000〜10,000歩、1日1.5〜3時間程度の移動や作業。'],['1.725','肉体労働中心','運搬・建設など負荷のある作業が多い。運動を除き10,000歩以上や1日3時間以上の身体作業が目安。']];
function renderSettings(){const p=store.profile||{};$('profileHeight').value=p.height??'';$('profileBirth').value=p.birth??'';$('profileSex').value=p.sex??'';$('specialCondition').checked=!!p.special;$('activityChoices').innerHTML='';for(const [value,title,hint] of activityOptions){const label=document.createElement('label');label.className='activity-option';label.innerHTML=`<input type="radio" name="activity" value="${value}" ${Number(p.lifeActivity)===Number(value)?'checked':''}><b>${title}（×${value}）</b><span>${hint}</span>`;$('activityChoices').append(label)}$('activityMigration').classList.toggle('hidden',p.lifeActivity!==null);targetsDraft={kcal:2000,p:130,f:60,c:235,...C.clone(store.foodTargets||{})};targetsDraft.locks={p:false,f:false,c:false,...(targetsDraft.locks||{})};targetsDraft.mode=targetsDraft.mode||'g';$('purpose').value=targetsDraft.purpose||'custom';$('macroMode').value=targetsDraft.mode;$('targetKcal').value=targetsDraft.kcal;renderMacros();const g=C.goalAt(store,today()),latest=C.weightAt(store,today());$('goalCurrent').value=latest?.weight??g?.current??'';$('goalTarget').value=g?.target??'';$('goalMonths').value=g?.months??12;$('goalMonthsRange').value=$('goalMonths').value;$('goalExerciseWeekly').value=g?.exerciseWeeklyKcal??0;$('goalExerciseRange').value=Math.min(5000,Number($('goalExerciseWeekly').value)||0);renderGoalPreview();$('suggestionBox').classList.add('hidden')}
function saveProfile(){const height=$('profileHeight').value,birth=$('profileBirth').value,sex=$('profileSex').value,activity=document.querySelector('input[name=activity]:checked')?.value;if(!C.numeric(height)||height<80||height>250||C.age(birth,today())===null||!['male','female'].includes(sex)||!activity){notice('身長・生年月日・性別・生活活動を確認してください');return}const next=C.clone(store);next.profile={...(next.profile||{}),height,birth,sex,lifeActivity:Number(activity),special:$('specialCondition').checked};if(persist(next)){cleanSection('profile');$('activityMigration').classList.add('hidden');renderGoalPreview();notice('プロフィールを保存しました')}}
function macroMessage(s){$('macroMessage').textContent=s;$('macroMessage').classList.toggle('hidden',!s)}
function renderMacros(){const root=$('macroControls');root.innerHTML='';$('targetKcal').value=roundPlain(targetsDraft.kcal);for(const [f,name] of [['p','タンパク質 P'],['f','脂質 F'],['c','炭水化物 C']]){const value=targetsDraft.mode==='percent'?Number(targetsDraft[f])*C.factors[f]/targetsDraft.kcal*100:Number(targetsDraft[f]),max=targetsDraft.mode==='percent'?100:targetsDraft.kcal/C.factors[f],box=document.createElement('div');box.className='macro';box.innerHTML=`<div class="row"><b>${name}</b><button id="lock_${f}" class="outline" aria-pressed="${!!targetsDraft.locks[f]}" aria-label="${name}を${targetsDraft.locks[f]?'解除':'ロック'}">${targetsDraft.locks[f]?'🔒 固定':'🔓 調整可'}</button></div>`;const label=document.createElement('label');label.className='row';label.innerHTML=`<input id="macro_${f}" class="macro-number" type="number" min="0" max="${max}" step="0.1" inputmode="decimal" value="${roundPlain(value)}" ${targetsDraft.locks[f]?'disabled':''} aria-label="${name} ${targetsDraft.mode==='percent'?'%':'g'}"><span>${targetsDraft.mode==='percent'?'%':'g'} <small>（${round(targetsDraft[f],1)} g / ${round(Number(targetsDraft[f])*C.factors[f]/targetsDraft.kcal*100,1)}%）</small></span>`;box.append(label);const slider=document.createElement('input');slider.type='range';slider.id='range_'+f;slider.min='0';slider.max=max;slider.step='0.1';slider.value=value;slider.disabled=!!targetsDraft.locks[f];slider.setAttribute('aria-label',name+' スライダー');slider.oninput=()=>commitMacro(f,slider.value,true);box.append(slider);root.append(box);$('lock_'+f).onclick=()=>{targetsDraft.locks[f]=!targetsDraft.locks[f];markDirty('targets');renderMacros();macroMessage('')};$('macro_'+f).onchange=e=>commitMacro(f,e.target.value)}const total=C.keys.reduce((a,k)=>a+Number(targetsDraft[k])*C.factors[k],0);$('macroSummary').textContent=`配分合計 ${round(total,2)} kcal ／ 目標 ${round(targetsDraft.kcal,2)} kcal。鍵はg値を固定します。`+(Math.abs(total-targetsDraft.kcal)>.01?' 既存目標は不一致のまま保持しています。いずれかの値を変更して配分を調整してください。':'')}
function roundPlain(n){return Math.round(Number(n)*100)/100}
function commitMacro(f,text,slider=false){if(text===''||!Number.isFinite(Number(text))){macroMessage('入力を確定するときは0以上の数値を入れてください。');return false}const value=f==='kcal'?Number(text):targetsDraft.mode==='percent'?Number(text)*targetsDraft.kcal/100/C.factors[f]:Number(text),result=C.allocate(targetsDraft,f,value);if(result.error){macroMessage(result.error);if(slider)refreshMacroNumbers();return false}targetsDraft=result.value;targetsDraft.purpose='custom';$('purpose').value='custom';markDirty('targets');macroMessage('');if(slider)refreshMacroNumbers();else renderMacros();return true}
function commitTargetInputs(){// change events normally fire on blur; explicitly validate visible fields before saving.
if($('targetKcal').value===''||!C.nonnegative($('targetKcal').value)||Number($('targetKcal').value)<=0){macroMessage('摂取カロリー目標を入力してください。');return false}if(Math.abs(Number($('targetKcal').value)-targetsDraft.kcal)>.005&&!commitMacro('kcal',$('targetKcal').value))return false;for(const k of C.keys){const inp=$('macro_'+k);if(inp.value===''||!C.nonnegative(inp.value)){macroMessage('PFCの空欄を確定してください。');return false}const shown=targetsDraft.mode==='percent'?targetsDraft[k]*C.factors[k]/targetsDraft.kcal*100:targetsDraft[k];if(Math.abs(Number(inp.value)-shown)>.011&&!commitMacro(k,inp.value))return false}return true}
function saveTargets(){if(!commitTargetInputs())return;const sum=C.keys.reduce((a,k)=>a+targetsDraft[k]*C.factors[k],0);if(Math.abs(sum-targetsDraft.kcal)>.01){macroMessage('目標カロリーとPFC配分を一致させてから保存してください。既存値は保持されています。');return}if(targetsDraft.kcal<1000||targetsDraft.kcal>10000){macroMessage('このアプリでは目標を1,000〜10,000 kcalの範囲で保存してください。極端な目標は個別に相談してください。');return}if(targetsDraft.kcal<1500&&!confirm('1,500 kcal未満の設定です。自動提案の範囲外です。個別に確認した値として保存しますか？'))return;const next=C.clone(store);next.foodTargets={...(next.foodTargets||{}),...C.clone(targetsDraft)};next.foodTargetHistory=[...(next.foodTargetHistory||[]),{date:today(),createdAt:new Date().toISOString(),targets:C.clone(targetsDraft)}];if(persist(next)){cleanSection('targets');notice('食事目標と鍵・表示単位を保存しました')}}
function showSuggestion(){const type=$('purpose').value,result=C.suggestion(store,today(),type,goalDraft),box=$('suggestionBox');box.classList.remove('hidden');if(result.error){box.textContent=result.error;return}const v=result.value;box.innerHTML=`<b>初期提案：${round(v.kcal)} kcal / 日</b><p>P ${round(v.p,1)} g ／ F ${round(v.f,1)} g ／ C ${round(v.c,1)} g</p><p class="hint">${esc(result.note)}</p>`;box.append(button('この提案を編集欄に適用',()=>{if(C.keys.some(k=>targetsDraft.locks[k])){macroMessage('ロック中の値を守るため提案の一括適用は止めました。必要な鍵を自分で解除してください。');return}targetsDraft={...targetsDraft,...v};markDirty('targets');renderMacros();macroMessage('提案を適用しました。自由に調整してから保存してください。')}))}
function goalWarning(g){if(!g)return '開始体重・目標体重・期間を入力してください。';
const weekly=Number($('goalExerciseWeekly').value);if(!Number.isFinite(weekly)||weekly<0||weekly>10000)return '週間運動目標は0〜10,000 kcalで入力してください。';
const lossPerWeek=(g.current-g.target)/C.daysBetween(g.end,g.start)*7,base=C.baseEnergy(store,today()),height=Number(store.profile?.height),bmi=height?g.target/(height/100)**2:null;
if(bmi&&bmi<18.5&&g.target<g.current)return '目標体重がBMI 18.5未満です。減量の自動提案は行いません。目標を見直してください。';
if(Math.abs(g.daily)>750||lossPerWeek>g.current*.01){const minMonths=Math.max(Math.ceil(Math.abs(g.target-g.current)*7700/(500*30.44)),1);return `期間が短く変化が大きい目標です。少なくとも約${minMonths}か月など、期間延長を検討してください。食事目標への自動反映は停止します。`}
const plan=base?C.exercisePlan(g,base.life,weekly):null;
if(plan&&plan.intakeDaily<1500)return '運動計画を考慮した参考摂取量が1,500 kcal未満になるため、食事目標へ反映しません。期間・運動目標を見直してください。';
if(weekly>5000)return '運動目標が高めです。継続できる範囲か確認してください。自動反映は停止します。';
return ''}
function renderGoalPreview(){
const weekly=Number($('goalExerciseWeekly').value);goalDraft=C.goal(today(),$('goalCurrent').value,$('goalTarget').value,Number($('goalMonths').value));
const g=goalDraft,warning=goalWarning(g),base=C.baseEnergy(store,today()),plan=g&&base?C.exercisePlan(g,base.life,weekly):null;
$('goalPreview').innerHTML=g?`<p>達成予定日 <b>${g.end}</b><br>月間の体重変化 ${signedDecimal(g.monthly)} kg / 月<br>週間カロリー収支の参考目標 <b>${signed(g.weekly)} kcal / 週</b></p>`+
`<p>週間運動消費目標 <b>${round(weekly)} kcal / 週</b> <small>（1日平均 ${round(weekly/7)} kcal）</small></p>`+
(plan?`<p>運動計画の食事反映（70％）：${round(plan.creditedWeekly)} kcal / 週<br>食事で確保する週間収支の目安：${signed(plan.foodWeekly)} kcal / 週 <small>（1日平均 ${signed(plan.foodDaily)} kcal）</small><br><b>提案する摂取カロリー目標：${round(plan.intakeDaily)} kcal / 日</b></p>`:'<p class="hint">摂取カロリーの提案にはプロフィール・体重の設定が必要です。</p>')+
(warning?'<p class="warning">'+esc(warning)+'</p>':''):'<p class="hint">'+esc(warning)+'</p>';
$('useGoalCalories').disabled=!plan||!!warning;
}
function signedDecimal(n){return (n>0?'+':n===0?'±':'')+round(n,2)}
function saveGoal(){renderGoalPreview();if(!goalDraft){notice('体重と期間を確認してください');return}const warning=goalWarning(goalDraft);if(warning&&!confirm(warning+'\nこの参考目標を保存しますか？ 食事目標は変更しません。'))return;const next=C.clone(store);next.goalHistory.push({...C.clone(goalDraft),exerciseWeeklyKcal:Number($('goalExerciseWeekly').value),exerciseCreditRate:.7,createdAt:new Date().toISOString()});if(persist(next)){cleanSection('goal');notice('体重目標を保存しました。食事目標は別途適用してください')}}
function applyGoalCalories(){renderGoalPreview();const base=C.baseEnergy(store,today());if(!goalDraft||goalWarning(goalDraft)||!base){notice('プロフィール・体重目標を確認してください');return}const plan=C.exercisePlan(goalDraft,base.life,Number($('goalExerciseWeekly').value));if(!plan){notice('運動目標を確認してください');return}const v=plan.intakeDaily;if(!confirm('参考値 '+round(v)+' kcalを食事目標の編集欄に適用しますか？ ロック中のPFCは維持します。'))return;commitMacro('kcal',v)}
function renderGraphs(){const isWeight=graphMode==='weight';$('weightGraphTab').classList.toggle('active',isWeight);$('balanceGraphTab').classList.toggle('active',!isWeight);$('weightGraphControls').classList.toggle('hidden',!isWeight);$('balanceGraphControls').classList.toggle('hidden',isWeight);$('graphDetail').textContent='点や棒をタップすると詳細が表示されます。';if(isWeight)renderWeightGraph();else renderBalanceGraph();renderMonthlyGoals()}
const SVGNS='http://www.w3.org/2000/svg';function svgEl(tag,attrs={},text){const e=document.createElementNS(SVGNS,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function chartBase(label){const svg=svgEl('svg',{viewBox:'0 0 640 300',role:'img','aria-label':label});$('graph').replaceChildren(svg);return svg}
function tapMark(e,text){e.classList.add('hit');e.setAttribute('tabindex','0');e.setAttribute('role','button');e.setAttribute('aria-label',text);const title=svgEl('title',{},text);e.append(title);e.onclick=()=>$('graphDetail').textContent=text;e.onkeydown=evt=>{if(evt.key==='Enter'||evt.key===' '){evt.preventDefault();$('graphDetail').textContent=text}}}
function renderWeightGraph(){const all=Object.entries(store.days).filter(([d,v])=>C.numeric(v.weight)&&Number(v.weight)>0&&d<=today()).map(([d,v])=>({date:d,weight:Number(v.weight)})).sort((a,b)=>a.date.localeCompare(b.date)),period=$('graphPeriod').value,end=today(),start=period==='all'?(all[0]?.date||C.plusMonths(end,-1)):C.plusMonths(end,-Number(period)),points=all.filter(x=>x.date>=start),svg=chartBase('体重推移。実測、7日移動平均、目標体重。');const goalPoints=[];for(let d=start;d<=end;d=C.plusDays(d,1)){const g=C.goalAt(store,d),v=C.targetWeight(g,d);if(v!==null)goalPoints.push({date:d,weight:v,goal:g.start+(g.createdAt||'')})}const values=[...points,...goalPoints].map(x=>x.weight);if(!points.length){svg.append(svgEl('text',{x:320,y:140,'text-anchor':'middle'},'この期間の体重記録はありません'));$('graphNote').textContent='体重を保存すると実測の点を表示します。';return}let min=Math.min(...values),max=Math.max(...values),pad=Math.max(.5,(max-min)*.15);min-=pad;max+=pad;const x=d=>52+C.daysBetween(d,start)/Math.max(1,C.daysBetween(end,start))*570,y=v=>245-(v-min)/(max-min)*205;for(let i=0;i<5;i++){const v=min+(max-min)*i/4;svg.append(svgEl('line',{x1:52,x2:622,y1:y(v),y2:y(v),stroke:'#dce4d6'}),svgEl('text',{x:44,y:y(v)+4,'text-anchor':'end'},round(v,1)))}svg.append(svgEl('text',{x:12,y:18},'kg'));for(let i=0;i<=3;i++){const d=C.plusDays(start,Math.round(C.daysBetween(end,start)*i/3));svg.append(svgEl('text',{x:x(d),y:274,'text-anchor':i===0?'start':i===3?'end':'middle'},d.slice(2)))}const line=(arr,color,dash)=>{if(!arr.length)return;svg.append(svgEl('polyline',{points:arr.map(p=>x(p.date)+','+y(p.weight)).join(' '),fill:'none',stroke:color,'stroke-width':2.5,...(dash?{'stroke-dasharray':dash}:{})}))};const groups=[];for(const p of goalPoints){if(!groups.length||groups.at(-1)[0].goal!==p.goal)groups.push([]);groups.at(-1).push(p)}groups.forEach(g=>line(g,'#b17787','5 4'));if($('showAverage').checked)line(points.map(p=>({...p,weight:C.movingAverage(all,p.date)})),'#9aa574','3 3');line(points,'#355B47');for(const p of points){const hit=svgEl('circle',{cx:x(p.date),cy:y(p.weight),r:9,fill:'#355B47','fill-opacity':.12});tapMark(hit,p.date+'：実測 '+p.weight+' kg ／ 7日間の記録平均 '+round(C.movingAverage(all,p.date),2)+' kg');svg.append(hit,svgEl('circle',{cx:x(p.date),cy:y(p.weight),r:3,fill:'#355B47','pointer-events':'none'}))}svg.onclick=evt=>{const pos=(evt.clientX-svg.getBoundingClientRect().left)/svg.getBoundingClientRect().width*640;const p=points.reduce((a,b)=>Math.abs(x(a.date)-pos)<Math.abs(x(b.date)-pos)?a:b);$('graphDetail').textContent=p.date+'：実測 '+p.weight+' kg ／ 7日間の記録平均 '+round(C.movingAverage(all,p.date),2)+' kg'};$('graphNote').textContent='緑実線：実測 ／ ピンク点線：当時の目標 ／ オリーブ点線：7日移動平均（未記録日は除外）。'+(points.length===1?'記録は1点です。傾向を見るには追加の記録が必要です。':'')}
function renderBalanceGraph(){const w=C.week(store,graphWeek,today()),svg=chartBase('月曜から日曜のカロリー収支。緑は消費超過、赤は摂取超過。');$('graphWeekLabel').textContent=w.start.slice(5)+'〜'+w.end.slice(5);const vals=w.values.filter(x=>x.balance!==null).map(x=>x.balance),max=Math.max(500,...vals.map(Math.abs)),y=v=>145-v/max*105;for(const v of [-max,0,max])svg.append(svgEl('line',{x1:56,x2:630,y1:y(v),y2:y(v),stroke:v===0?'#899b87':'#dde4d5'}),svgEl('text',{x:48,y:y(v)+4,'text-anchor':'end'},round(v)));svg.append(svgEl('text',{x:8,y:20},'kcal'));w.values.forEach((p,i)=>{const x=65+i*80;svg.append(svgEl('text',{x:x+28,y:277,'text-anchor':'middle'},['月','火','水','木','金','土','日'][i]));if(p.balance===null){svg.append(svgEl('text',{x:x+28,y:165,'text-anchor':'middle'},'未算出'));return}const rect=svgEl('rect',{x,y:Math.min(145,y(p.balance)),width:56,height:Math.max(3,Math.abs(145-y(p.balance))),rx:4,fill:p.balance<0?'#568565':p.balance>0?'#b85164':'#889581'});tapMark(rect,p.date+'：カロリー収支 '+signed(p.balance)+' kcal'+(p.provisional?'（暫定）':''));svg.append(rect)});svg.onclick=evt=>{const pos=(evt.clientX-svg.getBoundingClientRect().left)/svg.getBoundingClientRect().width*640;const p=w.values[Math.max(0,Math.min(6,Math.round((pos-93)/80)))];$('graphDetail').textContent=p.date+'：'+(p.balance===null?'未算出（未記録を含む）':'カロリー収支 '+signed(p.balance)+' kcal'+(p.provisional?'（暫定）':''))};$('graphNote').textContent=`記録済み累計：${w.count?signed(w.sum)+' kcal':'未算出'} ／ 週間目標：${w.target===null?'未設定':signed(w.target)+' kcal'}。未記録は0としていません。${w.complete<7?'入力不足のため暫定です。':''}`}
function renderMonthlyGoals(){const root=$('monthlyGoals'),g=C.goalAt(store,today());if(!g){root.innerHTML='<p class="hint">設定で体重目標と期間を保存してください。</p>';return}let html='<p class="hint">現在の計画 '+g.start+'〜'+g.end+'。月間の実測平均と比較します。過去の計画は保持しています。</p><div class="table-scroll"><table><thead><tr><th>目標日</th><th>目標 kg</th><th>実測平均 kg</th></tr></thead><tbody>';for(let n=1;n<=g.months;n++){const d=C.plusMonths(g.start,n),target=C.targetWeight(g,d),month=d.slice(0,7),weights=Object.entries(store.days).filter(([day,v])=>day.startsWith(month)&&day<=today()&&C.numeric(v.weight)&&Number(v.weight)>0).map(([,v])=>Number(v.weight));html+=`<tr><td>${d}</td><td>${round(target,1)}</td><td>${weights.length?round(weights.reduce((a,b)=>a+b,0)/weights.length,1):'未記録'}</td></tr>`}html+='</tbody></table></div>';root.innerHTML=html;const latest=C.weightAt(store,today()),reached=latest&&(g.current>g.target?latest.weight<=g.target:g.current<g.target?latest.weight>=g.target:Math.abs(latest.weight-g.target)<.5);if(reached){const div=document.createElement('div');div.className='soft';div.textContent='目標付近に到達しています。今後は維持モードへの切り替えを検討できます。';div.append(button('維持目標を設定',()=>{switchTab('settings');$('goalCurrent').value=latest.weight;$('goalTarget').value=latest.weight;renderGoalPreview();$('purpose').value='maintain';markDirty('goal');markDirty('targets')}));root.prepend(div)}}
function exportBackup(){download({app:'chapi-training',version:2,schemaRevision:3,store},'chapi-fit-backup-'+today()+'.json')}
async function importBackup(file){if(!file)return;try{if(file.size>50*1024*1024)throw Error('50 MBを超えるファイルです');const obj=JSON.parse(await file.text());if(obj.app!=='chapi-training')throw Error('Chapi Fitのバックアップではありません');const incoming=C.migrate(obj.store||(obj.data?C.fromV1(obj.data):null));const n=Object.keys(incoming.days).length;if(!confirm(`${n}日分の記録・${incoming.templates.length}件のメニューで、現在の記録と設定を置き換えますか？\n現在の保存データは復元前コピーとして端末内に残します。`))return;if(blocked&&(!recoveryExported||externalConflict)){notice(externalConflict?'別タブの更新を確認するため再読み込みしてください。':'元データを保護中です。まず元データを書き出してから復旧してください。');return}const wasBlocked=blocked;if(wasBlocked){localStorage.setItem('chapi-training-corrupt-original',rawOriginal);blocked=false}else localStorage.setItem(RESTORE,JSON.stringify(store));if(persist(incoming)){chooseDate(current);refreshPickers();renderSettings();dirtySections.clear();settingsDirty=false;$('fatal').classList.add('hidden');notice('バックアップを復元しました')}else if(wasBlocked)blocked=true}catch(e){notice('復元を中止しました：'+e.message)}finally{$('importFile').value=''}}
function rollover(){const now=today();if(now===loadedToday)return;$('rollover').classList.remove('hidden');$('rollover').replaceChildren(document.createTextNode('日付が変わりました。現在の入力は '+current+' のまま保持しています。 '),button('今日の記録へ',()=>{if(changeDate(now)){$('rollover').classList.add('hidden');loadedToday=now;switchTab('record')}}))}

function refreshMacroNumbers(){for(const k of C.keys){const v=targetsDraft.mode==='percent'?targetsDraft[k]*C.factors[k]/targetsDraft.kcal*100:targetsDraft[k];$('macro_'+k).value=roundPlain(v);$('range_'+k).value=v;$('macro_'+k).nextElementSibling.innerHTML=(targetsDraft.mode==='percent'?'%':'g')+' <small>（'+round(targetsDraft[k],1)+' g / '+round(targetsDraft[k]*C.factors[k]/targetsDraft.kcal*100,1)+'%）</small>'}const sum=C.keys.reduce((a,k)=>a+targetsDraft[k]*C.factors[k],0);$('macroSummary').textContent='配分合計 '+round(sum,2)+' kcal ／ 目標 '+round(targetsDraft.kcal,2)+' kcal。鍵はg値を固定します。'}
for(const [id,key,name] of [['exportRestore',RESTORE,'before-restore'],['exportDeleted','chapi-training-before-delete','before-delete']])$(id).onclick=()=>{const raw=localStorage.getItem(key);if(!raw){notice('該当するコピーはありません');return}download({app:'chapi-training',version:2,store:JSON.parse(raw)},'chapi-fit-'+name+'.json')};

// Bind fixed controls.
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('openSettings').onclick=()=>switchTab('settings');$('recordDate').onchange=()=>changeDate($('recordDate').value);$('weight').oninput=()=>{draft.weight=$('weight').value;renderEnergy()};$('daynote').oninput=()=>draft.note=$('daynote').value;$('saveDay').onclick=saveDay;$('saveFood').onclick=saveDay;$('copyDay').onclick=()=>{sync();copy(dayReport(current,draft))};$('copyFood').onclick=()=>copy('【Chapi Fit 食事 '+current+'】\n'+foodReport(draft));$('restDay').onchange=()=>{draft.restDay=$('restDay').checked;renderEnergy()};$('mascot').onclick=()=>{$('mascotMessage').textContent=$('mascot').dataset.message;$('mascotMessage').classList.toggle('hidden')};$('foodComplete').onchange=()=>draft.foodComplete=$('foodComplete').checked;$('strengthTotalMinutes').oninput=e=>updateStrengthTotal('minutes',e.target.value);$('strengthTotalKcal').oninput=e=>updateStrengthTotal('kcal',e.target.value);$('strengthTotalType').onchange=e=>updateStrengthTotal('energyType',e.target.value);$('addStrengthSession').onclick=()=>addSession('strength');$('addCardioSession').onclick=()=>addSession('cardio');$('prevMonth').onclick=()=>{month=C.plusMonths(month,-1);renderCalendar()};$('nextMonth').onclick=()=>{month=C.plusMonths(month,1);renderCalendar()};$('newTemplate').onclick=()=>startEditor();$('templateName').oninput=()=>{if(editing)editing.name=$('templateName').value};$('newStrengthItem').onclick=()=>{editing.items.push({id:uid(),name:'新しい筋トレ',kind:'strength',kg:0,sets:3,target:'10〜12回'});renderEditor()};$('newCardioItem').onclick=()=>{editing.items.push({id:uid(),name:'有酸素運動',kind:'cardio'});renderEditor()};$('cancelTemplate').onclick=()=>{if(editing&&!confirm('メニュー編集を保存せず閉じますか？'))return;editing=null;$('templateEditor').classList.add('hidden')};$('saveTemplate').onclick=saveTemplate;$('saveProfile').onclick=saveProfile;$('targetKcal').onchange=e=>commitMacro('kcal',e.target.value);$('macroMode').onchange=()=>{targetsDraft.mode=$('macroMode').value;markDirty('targets');renderMacros()};$('unlockAll').onclick=()=>{targetsDraft.locks={p:false,f:false,c:false};markDirty('targets');renderMacros();macroMessage('')};$('saveTargets').onclick=saveTargets;$('suggestTargets').onclick=showSuggestion;
for(const id of ['goalCurrent','goalTarget','goalMonths'])$(id).oninput=()=>{markDirty('goal');if(id==='goalMonths')$('goalMonthsRange').value=$('goalMonths').value;renderGoalPreview()};$('goalMonthsRange').oninput=()=>{$('goalMonths').value=$('goalMonthsRange').value;markDirty('goal');renderGoalPreview()};for(const [id,n] of [['monthsMinus',-1],['monthsPlus',1]])$(id).onclick=()=>{$('goalMonths').value=Math.max(1,Math.min(60,(Number($('goalMonths').value)||1)+n));$('goalMonthsRange').value=$('goalMonths').value;markDirty('goal');renderGoalPreview()};$('goalExerciseWeekly').oninput=()=>{markDirty('goal');$('goalExerciseRange').value=Math.min(5000,Number($('goalExerciseWeekly').value)||0);renderGoalPreview()};$('goalExerciseRange').oninput=()=>{$('goalExerciseWeekly').value=$('goalExerciseRange').value;markDirty('goal');renderGoalPreview()};$('saveGoal').onclick=saveGoal;$('useGoalCalories').onclick=applyGoalCalories;for(const event of ['input','change'])$('settings').addEventListener(event,e=>{const section=e.target.closest('[data-settings]')?.dataset.settings;if(section)markDirty(section)});$('exportBackup').onclick=exportBackup;$('importBackup').onclick=()=>$('importFile').click();$('importFile').onchange=e=>importBackup(e.target.files[0]);$('exportOriginal').onclick=()=>{const original=localStorage.getItem(BACKUP);if(original)download({app:'chapi-training',version:2,store:JSON.parse(original)},'chapi-fit-before-v3.json');else notice('更新前データはありません。通常のバックアップを書き出してください。')};
$('weightGraphTab').onclick=()=>{graphMode='weight';renderGraphs()};$('balanceGraphTab').onclick=()=>{graphMode='balance';renderGraphs()};$('graphPeriod').onchange=renderGraphs;$('showAverage').onchange=renderGraphs;$('prevWeek').onclick=()=>{graphWeek=C.plusDays(graphWeek,-7);renderGraphs()};$('nextWeek').onclick=()=>{graphWeek=C.plusDays(graphWeek,7);renderGraphs()};window.addEventListener('beforeunload',e=>{if(dayDirty()||settingsDirty||editing){e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover()});setInterval(rollover,60000);window.addEventListener('storage',e=>{if(e.key===KEY){blocked=true;externalConflict=true;$('fatal').classList.remove('hidden');$('fatal').textContent='別のタブで記録が更新されました。上書きを防ぐため保存を停止しました。必要な入力をコピーして再読み込みしてください。'}});
refreshPickers();chooseDate(current);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
// Public read-only diagnostics used by compatibility tests; no personal data is transmitted.
window.ChapiFit={version:VERSION,getStore:()=>C.clone(store),getDraft:()=>C.clone(draft),saveDay,changeDate,importBackup,rollover};
})();
