/* Chapi Fit: pure, local-date calculation model. No storage side effects. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ChapiCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),factors={p:4,f:9,c:4},keys=['p','f','c'];
const meals=[['breakfast','朝食'],['lunch','昼食'],['dinner','夕食'],['snack','間食']];
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function date(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;const [y,m,d]=s.split('-').map(Number),t=new Date(y,m-1,d,12);return iso(t)===s?t:null}
const plusDays=(s,n)=>{const d=date(s);d.setDate(d.getDate()+n);return iso(d)};
const daysBetween=(a,b)=>Math.round((Date.UTC(...a.split('-').map((x,i)=>Number(x)-(i===1?1:0)))-Date.UTC(...b.split('-').map((x,i)=>Number(x)-(i===1?1:0))))/86400000);
function plusMonths(s,n){const d=date(s),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return iso(d)}
function age(birth,on){const b=date(birth),d=date(on);if(!b||!d||b>d)return null;let a=d.getFullYear()-b.getFullYear();if(d.getMonth()<b.getMonth()||(d.getMonth()===b.getMonth()&&d.getDate()<b.getDate()))a--;return a<=120?a:null}
const numeric=x=>x!==''&&x!==null&&x!==undefined&&Number.isFinite(Number(x));
const nonnegative=x=>numeric(x)&&Number(x)>=0;
const defaults={bench:['DBベンチプレス',16,3,'8〜12回'],row:['チェストサポートロー',12,3,'10〜12回'],press:['DBショルダープレス',10,2,'8〜12回'],lateral:['サイドレイズ',4,2,'12〜15回'],curl:['インクラインカール',8,3,'10〜12回'],skull:['スカルクラッシャー',8,2,'10〜12回'],squat:['DBスクワット',16,3,'10〜15回'],rdl:['DB RDL',18,3,'10〜12回'],shrug:['DBシュラッグ',18,2,'12〜15回'],calf:['自重カーフレイズ',0,3,'15〜25回'],forearm:['前腕サーキット',6,2,'2周']};
const forearmNote='リストカール30秒 → リバースリストカール30秒 → スタンディング・リストカール30秒。各種目間休憩10秒。2周を基本とする。';
const plans={mon:['bench','row','press','lateral','curl','skull'],thu:['squat','rdl','shrug','calf','forearm'],sat:['squat','bench','row','rdl','press','lateral','shrug','calf','curl','skull']};
function item(id){const d=defaults[id];return {id,name:d[0],kind:'strength',kg:d[1],sets:d[2],target:d[3],...(id==='forearm'?{tracking:'rounds',rounds:2,annotation:forearmNote}:{})}}
function initialTemplates(){return [...Object.entries(plans).map(([id,ids])=>({id,name:{mon:'上半身のみ',thu:'下半身のみ',sat:'全身'}[id],items:ids.map(item)})),{id:'walk',name:'散歩',items:[{id:'walk',name:'散歩',kind:'cardio'}]},...newTemplates()]}
function newTemplates(){return [{id:'cf-forearm',name:'前腕サーキット',items:[item('forearm')]},{id:'cf-running',name:'ジョギング／ランニング',items:[{id:'running',name:'ジョギング／ランニング',kind:'cardio'}]},{id:'cf-stepper',name:'ステッパー',items:[{id:'stepper',name:'ステッパー',kind:'cardio',noDistance:true}]}]}
function fresh(){return {version:2,schemaRevision:3,templates:initialTemplates(),days:{},lastTemplate:'mon',profile:{lifeActivity:1.2},foodTargets:{kcal:2000,p:130,f:60,c:235,locks:{p:false,f:false,c:false},mode:'g',purpose:'custom'},goalHistory:[]}}
function validateStore(s){if(!s||typeof s!=='object'||!s.days||Array.isArray(s.days)||typeof s.days!=='object'||!Array.isArray(s.templates))throw Error('保存データの基本形式が不正です');for(const t of s.templates)if(!t||typeof t.name!=='string'||!Array.isArray(t.items)||t.items.some(i=>!i||typeof i!=='object'))throw Error('メニューの形式が不正です');for(const [k,d] of Object.entries(s.days)){if(!date(k)||!d||typeof d!=='object'||Array.isArray(d))throw Error('日付または日別記録が不正です');if(d.sessions!=null&&(!Array.isArray(d.sessions)||d.sessions.some(x=>!x||!Array.isArray(x.items)||x.items.some(i=>!i||typeof i!=='object'||i.sets!=null&&!Array.isArray(i.sets)))))throw Error('運動記録の形式が不正です');if(d.meals!=null&&(typeof d.meals!=='object'||Array.isArray(d.meals)))throw Error('食事記録の形式が不正です')};return true}
function fromV1(data){const s=fresh();s.schemaRevision=2;for(const [d,v] of Object.entries(data||{})){if(!date(d)||!v||typeof v!=='object')continue;const items=(plans[v.plan]||[]).filter(k=>v.exercises?.[k]).map(k=>({...item(k),sets:clone(v.exercises[k].sets||[]),note:v.exercises[k].note||''}));s.days[d]={...clone(v),weight:v.weight??'',calories:v.calories??'',note:v.note||'',sessions:items.length?[{id:'v1-'+d,templateId:v.plan,name:{mon:'上半身のみ',thu:'下半身のみ',sat:'全身'}[v.plan],items}]:[]}}return s}
function migrate(raw){validateStore(raw);const s=clone(raw);if((s.schemaRevision||0)<3){s.profile={...(s.profile||{})};if(s.profile.lifeActivity===undefined)s.profile.lifeActivity=s.profile.activity===undefined?1.2:null;s.foodTargets={kcal:2000,p:130,...(s.foodTargets||{})};s.foodTargets.locks={p:false,f:false,c:false,...(s.foodTargets.locks||{})};s.foodTargets.mode=s.foodTargets.mode||'g';s.foodTargets.purpose=s.foodTargets.purpose||'custom';const remain=Math.max(0,Number(s.foodTargets.kcal)-4*Number(s.foodTargets.p));if(!numeric(s.foodTargets.f))s.foodTargets.f=Math.min(Number(s.foodTargets.kcal)*.27,remain)/9;if(!numeric(s.foodTargets.c))s.foodTargets.c=Math.max(0,remain-9*Number(s.foodTargets.f))/4;for(const t of newTemplates())if(!s.templates.some(x=>x.id===t.id))s.templates.push(t);for(const t of s.templates)for(const i of t.items)if(i.id==='forearm'){if(i.annotation===undefined)i.annotation=forearmNote;if(i.tracking===undefined){i.tracking='rounds';i.rounds=2}}s.schemaRevision=3}s.goalHistory=s.goalHistory||[];return s}
function normalizeDay(d){return {...{weight:'',calories:'',note:'',sessions:[],meals:{}},...clone(d||{}),sessions:clone(d?.sessions||[]),meals:clone(d?.meals||{})}}
function weightAt(s,on,d){if(numeric(d?.weight)&&Number(d.weight)>0)return {weight:Number(d.weight),date:on};const ds=Object.keys(s.days).filter(k=>k<=on&&numeric(s.days[k].weight)&&Number(s.days[k].weight)>0).sort();if(!ds.length)return null;const k=ds.at(-1);return {weight:Number(s.days[k].weight),date:k}}
function baseEnergy(s,on,d){const p=s.profile||{},a=age(p.birth,on),w=weightAt(s,on,d),h=Number(p.height),activity=Number(p.lifeActivity);if(a===null||a<18||!w||!(h>=80&&h<=250)||!['male','female'].includes(p.sex)||![1.2,1.375,1.55,1.725].includes(activity))return null;const bmr=10*w.weight+6.25*h-5*a+(p.sex==='male'?5:-161);return bmr>0?{bmr,life:bmr*activity,activity,age:a,w}:null}
function exerciseEnergy(d,bmr){let net=0,raw=0,missing=0,unresolved=0;for(const sess of d.sessions||[])for(const it of sess.items||[]){if(!numeric(it.kcal)){missing++;continue}raw+=Number(it.kcal);if(!nonnegative(it.kcal)){unresolved++;continue}if(it.energyType==='net')net+=Number(it.kcal);else if(it.energyType==='gross'&&nonnegative(it.minutes)&&Number(it.minutes)>0&&bmr){net+=Math.max(0,Number(it.kcal)-bmr*Number(it.minutes)/1440)}else unresolved++}return {net,raw,missing,unresolved}}
function foodTotals(d){const t={kcal:0,p:0,f:0,c:0},count={kcal:0,p:0,f:0,c:0};for(const [key] of meals)for(const f of Object.keys(t)){const v=d.meals?.[key]?.[f];if(nonnegative(v)){t[f]+=Number(v);count[f]++}}return {total:t,count,complete:d.foodComplete===true||count.kcal===4,hasMark:Object.values(d.meals||{}).some(m=>m&&Object.values(m).some(v=>v!==''))}}
function energy(s,on,day){const d=day||normalizeDay(s.days[on]),base=baseEnergy(s,on,d),exercise=exerciseEnergy(d,base?.bmr),food=foodTotals(d),total=base&&!exercise.unresolved?base.life+exercise.net:null,balance=total!==null&&food.count.kcal>0?food.total.kcal-total:null;return {base,exercise,food,total,balance,provisional:!food.complete||exercise.missing>0||exercise.unresolved>0,legacy:nonnegative(d.calories)&&!d.legacyCaloriesResolved}}
function previous(s,id,on){for(const d of Object.keys(s.days).filter(x=>x<on).sort().reverse())for(const sess of [...(s.days[d].sessions||[])].reverse())for(const it of [...(sess.items||[])].reverse())if(it.id===id)return {date:d,item:it};return null}
function allocate(current,change,value){const t=clone(current),locks=t.locks||{},kcal=change==='kcal'?Number(value):Number(t.kcal);if(!Number.isFinite(kcal)||kcal<=0)return {error:'摂取カロリー目標は0より大きい数値にしてください。'};if(change!=='kcal'&&locks[change])return {error:'この栄養素はロックされています。'};if(!Number.isFinite(Number(value))||Number(value)<0)return {error:'0以上の数値を入力してください。'};t.kcal=kcal;if(change!=='kcal')t[change]=Number(value);const fixed=keys.filter(k=>locks[k]||k===change),free=keys.filter(k=>!fixed.includes(k)),used=fixed.reduce((sum,k)=>sum+Number(t[k])*factors[k],0),remaining=kcal-used;if(remaining< -1e-7)return {error:'固定したPFCがカロリー目標を超えます。値を戻すか、鍵を個別に解除してください。'};if(!free.length){if(Math.abs(remaining)>1e-7)return {error:'調整できる栄養素がありません。ロック値は保持しました。カロリー目標を戻すか、鍵を解除してください。'};return {value:t}}const prior=free.reduce((sum,k)=>sum+Math.max(0,Number(t[k]))*factors[k],0);let rest=Math.max(0,remaining);free.forEach((k,i)=>{const allocated=i===free.length-1?rest:Math.max(0,remaining)*(prior?Math.max(0,Number(t[k]))*factors[k]/prior:1/free.length);t[k]=allocated/factors[k];rest-=allocated});return {value:t}}
function goal(start,current,target,months){if(!date(start)||!numeric(current)||!numeric(target)||Number(current)<=0||Number(target)<=0||!Number.isInteger(Number(months))||months<1||months>60)return null;const end=plusMonths(start,Number(months)),days=daysBetween(end,start),delta=Number(target)-Number(current),daily=delta*7700/days;return {start,end,current:Number(current),target:Number(target),months:Number(months),daily,weekly:daily*7,monthly:delta/Number(months)}}
function goalAt(s,on){return [...(s.goalHistory||[])].filter(g=>g.start<=on).sort((a,b)=>a.start.localeCompare(b.start)||(a.createdAt||'').localeCompare(b.createdAt||'')).at(-1)||null}
function targetWeight(g,on){if(!g||on<g.start)return null;const f=Math.max(0,Math.min(1,daysBetween(on,g.start)/daysBetween(g.end,g.start)));return g.current+(g.target-g.current)*f}
function weekStart(on){const d=date(on);return plusDays(on,-((d.getDay()+6)%7))}
function week(s,on,today){const start=weekStart(on),dates=Array.from({length:7},(_,i)=>plusDays(start,i)),g=goalAt(s,on),target=g?(on>g.end?0:g.weekly):null;let sum=0,count=0,complete=0;const values=dates.map(day=>{if(day>today||!s.days[day])return {date:day,balance:null};const e=energy(s,day);if(e.balance!==null){sum+=e.balance;count++;if(!e.provisional)complete++}return {date:day,balance:e.balance,provisional:e.provisional}});const end=dates[6],remaining=today<start?7:today>end?0:daysBetween(end,today)+1;return {start,end,dates,values,target,sum,count,complete,remaining,left:target===null?null:target-sum,perDay:target!==null&&remaining?(target-sum)/remaining:null,rate:target===null||target===0?null:sum/target*100}}
function suggestion(s,on,purpose,goalDraft){const b=baseEnergy(s,on);const p=s.profile||{};if(!b)return {error:'先に成人のプロフィール・生活活動・体重を入力してください。'};if(p.special)return {error:'妊娠・授乳中、治療中などの場合は自動提案を使用せず、専門家と目標を設定してください。'};if(purpose==='custom')return {error:'カスタムでは現在の値をそのまま調整できます。'};const bmi=b.w.weight/(Number(p.height)/100)**2;if(bmi<18.5&&['loss','retain'].includes(purpose))return {error:'BMI 18.5未満の減量目標は自動提案しません。'};let kcal=b.life*(purpose==='loss'?.85:purpose==='retain'?.9:purpose==='gain'?1.05:1);kcal=Math.max(1500,kcal);const cap=25*(Number(p.height)/100)**2,goalW=goalDraft?.target||goalAt(s,on)?.target||b.w.weight,ref=Math.min(b.w.weight,Math.max(18.5*(Number(p.height)/100)**2,Math.min(cap,Number(goalW))));const trained=Object.entries(s.days).some(([d,v])=>d<=on&&d>=plusDays(on,-28)&&(v.sessions||[]).some(x=>x.items.some(i=>i.kind!=='cardio'&&(i.rounds||i.sets?.some(z=>z.done||Number(z.reps)>0)))));let pRate=purpose==='maintain'?(trained?1.4:1):purpose==='loss'?1.4:purpose==='retain'?1.8:1.6;const protein=Math.min(ref*pRate,kcal*.35/4),fat=Math.max(kcal*.25/9,ref*.6),carbs=(kcal-protein*4-fat*9)/4;if(carbs<0)return {error:'この条件では提案を作れません。プロフィールを確認してください。'};return {value:{kcal,p:protein,f:fat,c:carbs,purpose},note:`提案用参照体重 ${ref.toFixed(1)} kg、P ${pRate} g/kg。体格による過大提案を避けるため参照体重にBMI 25相当の上限を設けています（本アプリの保守的な設計）。個人の処方ではありません。`}}
function movingAverage(points,on){const values=points.filter(x=>x.date>=plusDays(on,-6)&&x.date<=on);return values.length?values.reduce((a,v)=>a+v.weight,0)/values.length:null}
return {clone,factors,keys,meals,iso,date,plusDays,plusMonths,daysBetween,age,numeric,nonnegative,defaults,forearmNote,initialTemplates,fresh,validateStore,fromV1,migrate,normalizeDay,weightAt,baseEnergy,exerciseEnergy,foodTotals,energy,previous,allocate,goal,goalAt,targetWeight,weekStart,week,suggestion,movingAverage};
});
